### ISSUE TITLE
正好需要element ui 2.0 一个暗黑主题

### ISSUE THREAD

**Issue by JohnnyZhang0628** [dongwei1125/theme-dark#1]
先试用一下

**Comment by dongwei1125** [comment]
如果有相关问题及时提交 issues 哦

**Comment by JohnnyZhang0628** [comment]
好的。作者有能力把element plus 的虚拟表格、虚拟下拉框、虚拟tree 移植成2.0的吗？这个很多人也有这个需求。不太想升3.0版本

**Comment by JohnnyZhang0628** [comment]
@dongwei1125 默认为黑色主题，会有闪屏的效果。就是先是白色，后面再是黑色

**Comment by dongwei1125** [comment]
@JohnnyZhang0628 提供一个可复现的最小 demo 呢
